name: Build

on:
  push:
    paths:
      - 'apps/**'
      - 'lib/**'
      - 'ports/**'
      - 'src/**'
      - '.github/actions/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build_util.yml'
      - '.github/workflows/build_ghostfat.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'apps/**'
      - 'lib/**'
      - 'ports/**'
      - 'src/**'
      - '.github/actions/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build_util.yml'
      - '.github/workflows/build_ghostfat.yml'
  repository_dispatch:
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.set-matrix-json.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Generate matrix json
        id: set-matrix-json
        run: |
          MATRIX_JSON=$(python .github/workflows/ci_set_matrix.py)
          echo "matrix=$MATRIX_JSON"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  # ---------------------------------------
  # Build ESP
  # ---------------------------------------
  espressif:
    needs: set-matrix
    uses: ./.github/workflows/build_util.yml
    secrets: inherit
    with:
      port: 'espressif'
      boards: ${{ toJSON(fromJSON(needs.set-matrix.outputs.json)['espressif'].board) }}
      build-system: 'make'
      toolchain: 'esp-idf'
      toolchain_version: 'v5.3.2'

  # ---------------------------------------
  # Unit testing with ghostfat
  # ---------------------------------------
  ghostfat:
    needs: set-matrix
    uses: ./.github/workflows/build_ghostfat.yml
    with:
        boards: ${{ toJSON(fromJSON(needs.set-matrix.outputs.json)['test_ghostfat'].board) }}
